name: GitHub Actions Build and Deploy

on:
  # 手动运行工作流程
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  #指定服务器的运行环境：最新版本ubuntu
    steps:
      # 使用actions/checkout@v4 库拉取代码到 ubuntu 上
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 根据网上资料查询此处可以设置为 false。https://github.com/actions/checkout
          persist-credentials: false

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install
      - run: npm run docs:build

      - name: Publish SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          strip_components: 2
          source: .vitepress/dist/
          target: /www/wwwroot/doer.ltd/
